version: "3.7"

volumes:
  db:

services:
  postgres-db:
    image: postgres:13-alpine
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: maveric_hub
      POSTGRES_idea: r_idea
      POSTGRES_PASSWORD: r_idea@123

  idea-service:
    container_name: idea-service
    build:
      context: ../idea-service
      dockerfile: Dockerfile
    image: idea-service:latest
    restart: always
    ports:
      - 4005:4005
    depends_on:
      - postgres-db
    links:
      - postgres-db:database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/maveric_hub
      - SPRING_DATASOURCE_ideaNAME=r_idea
      - SPRING_DATASOURCE_PASSWORD=r_idea@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update